module.exports = {
    content: ["./src/**/*.{html,ts}"],
 darkMode: "class",
    theme: {
      extend: {
        "colors": {
          "on-primary-fixed": "#370e00",
          "outline-variant": "#dbc1b8",
          "secondary": "#4b6456",
          "on-secondary-container": "#516a5c",
          "on-surface": "#1b1c1a",
          "secondary-container": "#cde9d8",
          "primary-container": "#d9774e",
          "tertiary": "#825505",
          "error-container": "#ffdad6",
          "on-tertiary-fixed-variant": "#643f00",
          "inverse-primary": "#ffb598",
          "background": "#fbf9f6",
          "on-primary": "#ffffff",
          "on-error": "#ffffff",
          "surface-container": "#efeeeb",
          "surface-container-low": "#f5f3f0",
          "surface-bright": "#fbf9f6",
          "on-surface-variant": "#55433c",
          "tertiary-container": "#bd8739",
          "on-primary-fixed-variant": "#7a2f0b",
          "surface-container-high": "#eae8e5",
          "outline": "#88726a",
          "surface-tint": "#994621",
          "primary-fixed": "#ffdbce",
          "tertiary-fixed": "#ffddb5",
          "tertiary-fixed-dim": "#f9bb68",
          "on-secondary-fixed-variant": "#344c3f",
          "surface-container-highest": "#e4e2df",
          "on-primary-container": "#501800",
          "on-tertiary-fixed": "#2a1800",
          "on-error-container": "#93000a",
          "error": "#ba1a1a",
          "secondary-fixed-dim": "#b2cdbc",
          "surface-container-lowest": "#ffffff",
          "surface-dim": "#dbdad7",
          "surface": "#FAF8F5",
          "surface-subtle": "#F4F0EA",
          "on-tertiary": "#ffffff",
          "on-background": "#1b1c1a",
          "on-secondary-fixed": "#082015",
          "on-tertiary-container": "#3e2500",
          "inverse-on-surface": "#f2f0ed",
          "primary-fixed-dim": "#ffb598",
          "secondary-fixed": "#cde9d8",
          "surface-variant": "#f0ece5",
          "primary": "#201F1E",
          "primary-accent": "#994621",
          "inverse-surface": "#30312f",
          "on-secondary": "#ffffff",
          "border-soft": "rgba(28, 25, 23, 0.07)"
        },
        "borderRadius": {
          "DEFAULT": "1rem",
          "lg": "1.5rem",
          "xl": "2rem",
          "2xl": "2.25rem",
          "3xl": "3rem",
          "full": "9999px"
        },
        "spacing": {
          "space-sm": "0.75rem",
          "margin": "2.5rem",
          "space-xs": "0.375rem",
          "margin-mobile": "1.25rem",
          "space-xl": "3.5rem",
          "gutter": "1.75rem",
          "space-lg": "2rem",
          "gutter-mobile": "1rem",
          "space-md": "1.25rem"
        },
        "fontFamily": {
          "sans": ["Plus Jakarta Sans", "sans-serif"],
          "body-lg": ["Plus Jakarta Sans", "sans-serif"],
          "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
          "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
          "body-sm": ["Plus Jakarta Sans", "sans-serif"],
          "label-md": ["Plus Jakarta Sans", "sans-serif"],
          "label-sm": ["Plus Jakarta Sans", "sans-serif"],
          "label-lg": ["Plus Jakarta Sans", "sans-serif"],
          "body-md": ["Plus Jakarta Sans", "sans-serif"],
          "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
          "headline-md": ["Plus Jakarta Sans", "sans-serif"],
          "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
          "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
          "display-lg": ["Plus Jakarta Sans", "sans-serif"]
        }
      },
    },
  }
Object.assign(module.exports.theme.extend.colors, {"mobile-primary-fixed-dim": "#ffb598", "mobile-outline-variant": "#dbc1b8", "mobile-on-surface": "#1b1c1a", "mobile-surface-bright": "#fbf9f6", "mobile-surface-variant": "#e4e2df", "mobile-inverse-surface": "#30312f", "mobile-on-tertiary-fixed": "#2a1800", "mobile-surface-container": "#efeeeb", "mobile-surface-container-lowest": "#ffffff", "mobile-on-primary-container": "#501800", "mobile-on-tertiary": "#ffffff", "mobile-primary-fixed": "#ffdbce", "mobile-background": "#fbf9f6", "mobile-tertiary": "#825505", "mobile-on-secondary": "#ffffff", "mobile-on-background": "#1b1c1a", "mobile-primary-container": "#d9774e", "mobile-surface-container-low": "#f5f3f0", "mobile-secondary-container": "#cde9d8", "mobile-secondary-fixed-dim": "#b2cdbc", "mobile-surface-tint": "#994621", "mobile-inverse-on-surface": "#f2f0ed", "mobile-on-primary": "#ffffff", "mobile-tertiary-fixed": "#ffddb5", "mobile-primary": "#994621", "mobile-error": "#ba1a1a", "mobile-on-error-container": "#93000a", "mobile-on-tertiary-fixed-variant": "#643f00", "mobile-on-tertiary-container": "#3e2500", "mobile-error-container": "#ffdad6", "mobile-on-surface-variant": "#55433c", "mobile-tertiary-container": "#bd8739", "mobile-on-error": "#ffffff", "mobile-outline": "#88726a", "mobile-inverse-primary": "#ffb598", "mobile-tertiary-fixed-dim": "#f9bb68", "mobile-on-primary-fixed-variant": "#7a2f0b", "mobile-surface-dim": "#dbdad7", "mobile-on-secondary-container": "#516a5c", "mobile-surface": "#fbf9f6", "mobile-surface-container-high": "#eae8e5", "mobile-surface-container-highest": "#e4e2df", "mobile-on-secondary-fixed": "#082015", "mobile-on-secondary-fixed-variant": "#344c3f", "mobile-secondary": "#4b6456", "mobile-on-primary-fixed": "#370e00", "mobile-secondary-fixed": "#cde9d8"});
module.exports.theme.extend.fontSize = Object.assign(module.exports.theme.extend.fontSize ?? {}, {"body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}], "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}], "headline-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600"}], "display-lg": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "700"}], "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}], "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}], "headline-sm": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.005em", "fontWeight": "600"}], "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "600"}], "body-md": ["15px", {"lineHeight": "24px", "fontWeight": "400"}], "body-sm": ["13px", {"lineHeight": "20px", "fontWeight": "400"}], "display-lg-mobile": ["38px", {"lineHeight": "46px", "letterSpacing": "-0.02em", "fontWeight": "700"}], "headline-lg-mobile": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "600"}]});
